baseURL: "https://www.example.com/"
theme: "up-business-theme"
languageCode: "es-es"

title: "Motor Mecanic"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Motor Mecanic"
  description: "Taller especializado en mecánica en general, con mas de 15 años de experiencia."
  images: 
    - "images/logot.png"

  logo: "logot.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "Travesía Monasterio de Irache 1 31011 Pamplona, España"
    

  contact:
    - "motormecanic@gmail.com"
    - "948 25 22 48"

  copyright: "© 2024 Up Business All Rights Reserved by Víctor Rubio Ibáñez"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Que hacemos"
      url: "#services"
      weight: 2

    - name: "Nuestro equipo"
      url: "#brands"
      weight: 3

    - name: "Tarifas"
      url: "/gracias/"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Ponte en contacto"
      url: "/contacto/"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "¿Que hacemos?"
      url: "/#"
      weight: 2

    - name: "Nuestro equipo"
      url: "/#"
      weight: 3

    - name: "Tarifas"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
